DESCRIPTION

Mb-3377 Support 'slabs' and 'items' for stats

Allow stats script to pull 'slabs' and 'items' stats from
memcached bucket type. But for membase bucket, script will print
errors as:

Traceback (most recent call last):
  File "stats.py", line 261, in <module>
    main()
  File "stats.py", line 258, in main
    c.execute()
  File "c:\temp\clitool.py", line 42, in execute
    f[0](mc, *args[2:], **opts.__dict__)
  File "stats.py", line 37, in g
    f(*args[:n])
  File "stats.py", line 137, in stats_slabs
    stats_formatter(mc.stats('slabs'))
  File "c:\temp\mc_bin_client.py", line 255, in stats
    cmd, opaque, cas, klen, extralen, data = self._handleKeyedResponse(None)
  File "c:\temp\mc_bin_client.py", line 83, in _handleKeyedResponse
    raise MemcachedError(errcode,  rv)
  mc_bin_client.MemcachedError: Memcached error #1:  Not found

Change-Id: Ic84bb98e953548dbbbfa8c98f450b0af10125d41


COMMENTS

author: Rubi Walsh
date: 2011-02-10 20:11:28.332000000

Patch Set 1:

If we want to compress errors, we need to comment out statement to raise MemcachedError in mc_bin_client.

-------------------------------------
author: Noah Dean
date: 2011-02-11 08:07:48.842000000

Patch Set 1: I would prefer that you didn't submit this

(1 inline comment)

I think you mean suppress, and we don't want to ignore errors just because one command emits them.  We can capture it locally and report that the stat is not available from the requested engine.

Please remove the error from the commit message.  We don't need to document it not working here.

Line:42, management/stats -> What's with the weird spacing here?  And why did the formatter need to be changed?

-------------------------------------
author: Rubi Walsh
date: 2011-02-11 17:17:50.115000000

Patch Set 1:

When db is empty, stats items will return such error message as :

ValueError: max() arg is an empty sequence. 

The if statement will check such case instead of printing error trace.

-------------------------------------
