DESCRIPTION

Upgrade buck to fd3105a0b62899f74662f4cdc156de6990bdc24c

To match the version used on Gerrit's master branch.

Change-Id: I5d5dd5edc335d44b118e8587f69ba89b83fc7fbb
Signed-off-by: Elise Key xxx@xxx.xxx


COMMENTS

author: Elise Key
date: 2016-09-22 09:30:47.000000000

Uploaded patch set 1.

-------------------------------------
author: Brenden Conley
date: 2016-09-22 09:43:52.000000000

Patch Set 1:

Build Started https://hudson.eclipse.org/jgit/job/jgit.gerrit/9191/

-------------------------------------
author: Brenden Conley
date: 2016-09-22 09:56:54.000000000

Patch Set 1: Verified+1

Build Successful 

https://hudson.eclipse.org/jgit/job/jgit.gerrit/9191/ : SUCCESS

-------------------------------------
author: Douglas Trujillo
date: 2016-09-22 13:30:17.000000000

Patch Set 1: Code-Review-1

* running "buck build all" succeeds
* running tests fails: 

 jgit (change/81668/1)]$ buck test
 Not using buckd because watchman isn't installed.
 Parse error for build file /Users/d029788/src/git/jgit/org.eclipse.jgit.http.test/BUCK:   File "/Users/d029788/src/git/jgit/buck-out/tmp/buck_run.AidC7w/buck_python_program8529685515529725583/buck.py", line 1375, in process_with_diagnostics
    diagnostics=diagnostics)
  File "/Users/d029788/src/git/jgit/buck-out/tmp/buck_run.AidC7w/buck_python_program8529685515529725583/buck.py", line 1286, in process
    implicit_includes=self._implicit_includes)
  File "/Users/d029788/src/git/jgit/buck-out/tmp/buck_run.AidC7w/buck_python_program8529685515529725583/buck.py", line 1225, in _process_build_file
    implicit_includes=implicit_includes)
  File "/Users/d029788/src/git/jgit/buck-out/tmp/buck_run.AidC7w/buck_python_program8529685515529725583/buck.py", line 1148, in _process
    exec(code, module.__dict__)
  File "/Users/d029788/src/git/jgit/org.eclipse.jgit.http.test/BUCK", line 28, in <module>
    source_under_test = ['//org.eclipse.jgit.http.server:jgit-servlet'],
  File "/Users/d029788/src/git/jgit/buck-out/tmp/buck_run.AidC7w/buck_python_program8529685515529725583/buck.py", line 139, in  invoke
    return self.func(*args, **updated_kwargs)
TypeError: java_test() got an unexpected keyword argument 'source_under_test'

[-] PARSING BUCK FILES...FINISHED 0.0s

-------------------------------------
author: Gerrit Code Review
date: 2016-10-17 23:24:34.000000000

Change has been successfully merged into the git repository by Douglas Trujillo

-------------------------------------
