DESCRIPTION

CBQE-1845 test zone available when
upgrade cluster from community edition to enterprise edition

Change-Id: I92667e2ffda2849dedb20310c02387a10b020ca3


COMMENTS

author: Frederick Booker
date: 2014-03-22 01:25:48.438000000

Uploaded patch set 5.

-------------------------------------
author: Hugo Blankenship
date: 2014-03-22 01:25:56.048000000

Patch Set 5:

Build Started http://factory.couchbase.com/job/testrunner-Jasmin Rangel-master/771/

-------------------------------------
author: Frederick Booker
date: 2014-03-22 01:26:46.788000000

Patch Set 5: Verified+1

-------------------------------------
author: Hugo Blankenship
date: 2014-03-22 02:06:01.363000000

Patch Set 5: Verified-1

Build Failed 

http://factory.couchbase.com/job/testrunner-Jasmin Rangel-master/771/ : FAILURE

-------------------------------------
author: Esperanza Cherry
date: 2014-03-22 12:12:52.907000000

Patch Set 5:

(1 comment)

Line:313, pytests/rackzone/rackzonetests.py -> you raise Exception above, then catch it and only print it.
why the test not failed here?

-------------------------------------
author: Frederick Booker
date: 2014-03-24 18:58:04.645000000

Patch Set 5:

(1 comment)

Line:313, pytests/rackzone/rackzonetests.py -> In case above raise Exception, that the zone is not created.  It means upgrade from CE to EE failed to enable RZA.  For the seconds catch exception, it may relate to something else not relate to this test purpose/

-------------------------------------
author: Esperanza Cherry
date: 2014-03-24 20:49:26.855000000

Patch Set 5:

(1 comment)

Line:313, pytests/rackzone/rackzonetests.py -> try: 
 any_code
 raise Exception
except Exception:
  print

the inner "raise Exception" doesn't make sence

-------------------------------------
author: Tate Garrett
date: 2014-03-26 20:10:55.774000000

The change could not be merged due to a path conflict.

Please rebase the change locally and upload the rebased commit for review.

-------------------------------------
author: Tate Garrett
date: 2014-03-26 20:11:36.641000000

The change could not be merged due to a path conflict.

Please rebase the change locally and upload the rebased commit for review.

-------------------------------------
