DESCRIPTION

MB-100 Apply the new bucket data structure to _all_bucket_delete method.

This change fix the run error saw in centos-64-2.0-backup build 35 in jenkins
			Traceback (most recent call last):
  File "pytests/backup/opsduringbackup.py", line 48, in LoadDuringBackup
    self._all_buckets_delete(self.master)
  File "pytests/basetestcase.py", line 149, in _all_buckets_delete
    task.result()
  File "lib/tasks/future.py", line 156, in result
    return self.__get_result()
  File "lib/tasks/future.py", line 108, in __get_result
    raise self._exception
NameError: global name 's' is not defined
Now it is fix.

Change-Id: I75ad1d6a5a3f3083dfbf899dbd4f65881d88751f


COMMENTS

author: Roland Charles
date: 2012-08-02 20:27:48.640000000

Patch Set 1: Verified



-------------------------------------
author: Esperanza Cherry
date: 2012-08-02 21:21:12.508000000

Patch Set 1: Looks good to me, approved



-------------------------------------
author: Roland Charles
date: 2012-08-02 21:29:48.030000000

Change has been successfully cherry-picked as 0bcdf81a10392b34ff743cbac954fccda6fc08fa.

-------------------------------------
author: Hugo Blankenship
date: 2012-08-02 23:46:23.858000000

Patch Set 1:

Build Started http://qa.hq.northscale.net/job/testrunner-Jasmin Rangel-master/2193/ 

-------------------------------------
author: Hugo Blankenship
date: 2012-08-03 00:02:04.138000000

Patch Set 1:

Build Successful 

http://qa.hq.northscale.net/job/testrunner-Jasmin Rangel-master/2193/ : SUCCESS

-------------------------------------
