DESCRIPTION

CBQE-358:failover-tests:add attempts to get_bucket

failover tests are failed when try to get get_bucket() info to check
items count
set number of retries=3, timout=2

Change-Id: Ie2f15ace6d16a9448b2b59125f72d5ef8676f2a4


COMMENTS

author: Esperanza Cherry
date: 2012-07-23 22:33:29.353000000

Uploaded patch set 5.

-------------------------------------
author: Hugo Blankenship
date: 2012-07-24 02:57:40.554000000

Patch Set 5:

Build Started http://qa.hq.northscale.net/job/testrunner-Jasmin Rangel-master/1883/ 

-------------------------------------
author: Hugo Blankenship
date: 2012-07-24 03:26:14.077000000

Patch Set 5: Verified

Build Successful 

http://qa.hq.northscale.net/job/testrunner-Jasmin Rangel-master/1883/ : SUCCESS

-------------------------------------
author: Reid Stokes
date: 2012-07-25 18:26:30.094000000

Patch Set 5: Looks good to me, approved



-------------------------------------
author: Tate Garrett
date: 2012-07-25 19:06:27.280000000

Your change could not be merged due to a path conflict.

Please merge (or rebase) the change locally and upload the resolution for review.

-------------------------------------
