DESCRIPTION

update mc_bin_client to 1.8.1 version

Change-Id: Idb5a22ce0560388504cb217bed4dc63f495cda5f


COMMENTS

author: Ayden Rivas
date: 2012-04-14 02:49:20.920000000

Uploaded patch set 3.

-------------------------------------
author: Ayden Rivas
date: 2012-04-14 02:50:03.640000000

Patch Set 3:

I'm not sure why those were taken out of memcacheConstants, but I readded them.

-------------------------------------
author: Frederick Booker
date: 2012-04-14 23:06:17.860000000

Patch Set 3: Fails

Test failed.  Only one pike up to 2.5K ops at start then down to zero more than 10 minutes.  No thing happen


testrunner logs, diags and results are available under logs/testrunner-12-Apr-14_15-58-00
Thuans-MacBook-Pro:testrunner thuan$ ./testrunner -i ../../ini/one-mac129.ini -t memcapable.MultiGetNegativeTest.test_mc_multi_get
/Users/thuan/work/gertest/testrunner/logs/testrunner-12-Apr-14_15-58-47
  ./testrunner ../../ini/one-mac129.ini  -t memcapable.MultiGetNegativeTest.test_mc_multi_get
test_mc_multi_get (memcapable.MultiGetNegativeTest) ... ^CTraceback (most recent call last):
  File "./testrunner", line 211, in <module>
    result = unittest.TextTestRunner(verbosity=2).run(suite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 65, in __call__
    return self.run(*args, **kwds)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 103, in run
    test(result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 376, in __call__
    return self.run(*args, **kwds)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 318, in run
    testMethod()
  File "pytests/memcapable.py", line 1387, in test_mc_multi_get
    self._test_multi_get(self.onenodemc, 10 * 1000)
  File "pytests/memcapable.py", line 1419, in _test_multi_get
    gets = client.getMulti(keys)
  File "lib/mc_bin_client.py", line 319, in getMulti
    self._sendCmd(memcacheConstants.CMD_GETQ, v, '', k)
  File "lib/mc_bin_client.py", line 59, in _sendCmd
    vbucketId=self.vbucketId)
  File "lib/mc_bin_client.py", line 67, in _sendMsg
    _, w, _ = select.select([], [self.s], [], self.timeout)
KeyboardInterrupt

-------------------------------------
author: Ayden Rivas
date: 2012-04-15 00:06:42.536000000

Patch Set 3:

how many items were in a single multiget?

-------------------------------------
author: Ayden Rivas
date: 2012-04-15 00:10:15.726000000

Patch Set 3:

oh, looks like 10000. I think we need to decide what numbers make sense for a single multiget call.

-------------------------------------
author: Titus Ho
date: 2012-04-23 19:32:27.928000000

Patch Set 3:

Hey Keith, any update on when this will be ready?

-------------------------------------
author: Ayden Rivas
date: 2012-04-23 19:44:11.261000000

Patch Set 3:

im not 100% convinced there is a problem. if you request a lot of keys with a single operation it will take a while, and possibly time out.

-------------------------------------
author: Zackery Barr
date: 2012-04-23 19:46:12.771000000

Patch Set 3:

yeah if multi-get with 10k items is the only test that is failing we should not block this change

-------------------------------------
