DESCRIPTION

JCBC-329 : Added new view connection based tests

Change-Id: I75a4ddab1a51172a65342a2af91efb148b5cb374


COMMENTS

author: Yasmin Rush
date: 2013-08-01 10:59:55.969000000

Uploaded patch set 4.

-------------------------------------
author: Yasmin Rush
date: 2013-08-01 11:01:11.095000000

Patch Set 4: Verified+1

-------------------------------------
author: Natasha Sullivan
date: 2013-08-01 11:32:41.482000000

Patch Set 4: Code-Review-1

Hi,

looks good in general, but there is a slight glitch here.

When you catch the exception its good, but also you need to think of the case when we change the code. lets say we change it so that the exception is not thrown anymore (or even a different one), then it will not be caught and we can't assert it properly.

so you can do two things:

xxx@xxx.xxx = MyExpectedExceptionType.class)

or in your try block, at the bottom use something like assertTrue("something gone wrong...", false); so that if it hits that path its a failure!..
Do you agree with that observation?

-------------------------------------
author: Yasmin Rush
date: 2013-08-01 12:22:38.390000000

Patch Set 4:

I am not sure why would we not have an exception in case the connection is not established. Honestly, to me it does not make sense to have an assert there in the try block. The flow will anyway not go there.

-------------------------------------
