DESCRIPTION

CBQE-0: handle RuntimeError: maximum recursion depth exceeded

test hangs when we can't setMulti (_setMulti_seq) -> recursion many times and python throws RuntimeError: maximum recursion depth exceeded
http://qa.hq.northscale.net/job/centos_x64--02_01--basic_rebalance_tests-P0/8/consoleFull

Change-Id: I899e6e4a9d62d2b3c027a4fd997c787d4b801346


COMMENTS

author: Tate Garrett
date: 2014-03-11 14:00:20.419000000

The change could not be merged due to a path conflict.

Please rebase the change locally and upload the rebased commit for review.

-------------------------------------
author: Tate Garrett
date: 2014-03-18 14:53:26.602000000

The change could not be merged due to a path conflict.

Please rebase the change locally and upload the rebased commit for review.

-------------------------------------
author: Hugo Blankenship
date: 2014-03-18 15:44:36.547000000

Patch Set 3: Verified+1

Build Successful 

http://factory.couchbase.com/job/testrunner-Jasmin Rangel-master/731/ : SUCCESS

-------------------------------------
author: Esperanza Cherry
date: 2014-03-18 15:50:10.181000000

Patch Set 3: Code-Review+2

-------------------------------------
